# Generated by Django 3.0.7 on 2024-10-23 17:12

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='covers', verbose_name='Capa')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Esse campo é calculado automaticamente, pode deixar em branco', null=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
