version: '3.8'

services:
  web:
    container_name: web_django
    image: lucasfs/django_lwandisurf_dev:exposed
    restart: always
    hostname: web_django
    # build:
    #   context: ./django
    #   dockerfile: Dockerfile.dev
    volumes:
      - django_project:/app/web/
    env_file: 
      - ./env_files/.env.dev.web
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  db:
    container_name: db_postgres
    hostname: db_postgres
    restart: always
    image: lucasfs/postgres_lwandisurf_dev:1.0
    # build:
    #   context: ./postgres
    volumes:
      - postgres_backup:/backup/
    env_file: 
      - ./env_files/.env.dev.db

  ui:
    container_name: ui_react
    hostname: ui_react
    restart: always
    image: lwandisurf/node:latest
    stdin_open: true
    volumes:
      - './interface:/app'
      - '/app/node_modules'
    ports:
      - "3001:3000"

volumes:
  postgres_backup:
    driver: local
    driver_opts:
      type: none
      device: $PWD/volumes/postgres_backup
      o: bind
  
  django_project:
    driver: local
    driver_opts:
      type: none
      device: $PWD/django/app
      o: bind
