services:
  db-lwandi:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    env_file:
      - ./env_files/.env.prod.db

  lwandisurf_web:
#    image: lucasfs/lwandisurf-django:latest
    build:
      context: ./django
#      image: "lwandisurf-django"
    restart: always
    command: uwsgi --ini /app/web/uwsgi.ini
    volumes:
      - ./django/app/:/app/web
    env_file:
      - ./env_files/.env.prod.web
    depends_on:
      - db-lwandi


volumes:
  django_project: