version: '3.8'

services:
  db-lwandi:
    container_name: db-lwandi
    restart: always
    image: postgres:12.0-alpine
    networks:
      - proxy
    volumes:
      - $PWD/volumes/postgres:/var/lib/postgresql/data/
    env_file:
      - ./env_files/.env.prod.db

  django-lwandi:
    container_name: django-lwandi
    build:
      context: ./django
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - django_project:/app
    networks:
      - proxy
    env_file:
      - ./env_files/.env.prod.web
    depends_on:
      - db-lwandi

  nginx-lwandi:
    container_name: nginx-lwandi
    build: ./nginx
    restart: always
    volumes:
      - django_project:/app
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - django-lwandi
    environment:
      - ./env_files/.env.prod.nginx

#  ui:
#    container_name: ui_react
#    hostname: ui_react
#    restart: always
#    image: lwandisurf/node:latest
#    stdin_open: true
#    volumes:
#      - './interface:/app'
#      - '/app/node_modules'
#    ports:
#      - "3001:3000"


volumes:
  django_project:
  postgres_data:

networks:
  proxy:
    external:
      name: nginx-proxy