version: '3.8'

services:
  web:
    container_name: web_django
    build:
      context: ./django
    image: "django_web"
    restart: always
    env_file: 
      - ./env_files/.env.prod.web
    expose:
      - 8000
    depends_on:
      - db
      
  db:
    container_name: db_postgres
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - $PWD/volumes/postgres:/var/lib/postgresql/data/
    env_file: 
      - ./env_files/.env.prod.db

  nginx:
    container_name: nginx-lwandisurf
    build: ./nginx
    restart: always
    volumes:
      - api_data:/docker_api
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=lwandisurf.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=lwandisurf.org
      - LETSENCRYPT_EMAIL=admin@growtechnologies.com.br

volumes:
  static_data:
  media_data:

networks:
  proxy:
    external:
      name: nginx-proxy