version: '3.5'
services:
  nginx:
    container_name: nginx-lwandisurf
    build: ./nginx
    restart: always
    volumes:
      - api_data:/docker_api
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - api
    environment:
      - VIRTUAL_HOST=lwandisurf.org
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=lwandisurf.org
      - LETSENCRYPT_EMAIL=admin@growtechnologies.com.br

  api:
    container_name: api-lwandisurf
    build: ./api
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/docker_api
    networks:
      - proxy
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - proxy
    environment:
      - POSTGRES_USER=guris
      - POSTGRES_PASSWORD=guris753159
      - POSTGRES_DB=lwandisurf

volumes:
  api_data:
  postgres_data:

networks:
  proxy:
    external:
      name: nginx-proxy