# Generated by Django 3.0.7 on 2024-10-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lwandisurf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Sobre')),
                ('history', models.TextField(blank=True, null=True, verbose_name='História')),
                ('values', models.TextField(blank=True, null=True, verbose_name='Valores')),
            ],
            options={
                'verbose_name': 'Lwandisurf',
                'verbose_name_plural': 'Lwandisurf',
            },
        ),
    ]
