FROM python:3.8.3-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt /requirements.txt

# Install dependencies
RUN apk update \
    && apk add --no-cache libc-dev linux-headers postgresql-dev gcc python3-dev musl-dev

# Pillow dependencias
RUN apk add zlib-dev jpeg-dev libjpeg

RUN apk add --no-cache --virtual .build-deps libc-dev libxslt-dev zlib  && \
    apk add --no-cache libxslt && \
    pip install --no-cache-dir lxml>=3.5.0 && \
    apk del .build-deps

RUN pip install --upgrade pip                                    
RUN pip install -r /requirements.txt

# Create the appropriate directories
ENV APP_HOME=/app/web
RUN mkdir -p $APP_HOME

WORKDIR $APP_HOME

# copy project
COPY ./app $APP_HOME

ENV PATH="/scripts:${PATH}"

COPY ./scripts /scripts
RUN chmod +x /scripts/*

CMD ["entrypoint.sh"]

